export const PRODUCTS_LIST = 'PRODUCTS_LIST';
export const PRODUCTS_LIST_PENDING = 'PRODUCTS_LIST_PENDING';
export const PRODUCTS_LIST_FULFILLED = 'PRODUCTS_LIST_FULFILLED';
export const PRODUCTS_LIST_REJECTED = 'PRODUCTS_LIST_REJECTED';
