export const UPDATE_BRANDING_BASIC_FORM_VALUE = "UPDATE_BRANDING_BASIC_FORM_VALUE";
export const UPDATE_LOGO_AND_IMAGERY = "UPDATE_LOGO_AND_IMAGERY";
export const UPDATE_SOCIAL_MEDIA = "UPDATE_SOCIAL_MEDIA";
export const UPDATE_WEBSITE = "UPDATE_WEBSITE";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
