export const LOCATIONS_LIST = 'LOCATIONS_LIST';
export const LOCATIONS_LIST_PENDING = 'LOCATIONS_LIST_PENDING';
export const LOCATIONS_LIST_FULFILLED = 'LOCATIONS_LIST_FULFILLED';
export const LOCATIONS_LIST_REJECTED = 'LOCATIONS_LIST_REJECTED';
